import Link from "next/link";
import { Brand } from "@/components/brand";
import { ArrowRight, ArrowUpRight, CheckIcon } from "@/components/icons";

export default function LandingPage() {
  return <main className="landing">
    <header className="site-header"><Link href="/"><Brand /></Link><nav className="header-nav"><Link className="text-link" href="#method">Notre méthode</Link><Link className="text-link" href="#pricing">Tarifs</Link><Link className="button small" href="/auth">Commencer <ArrowUpRight size={14} /></Link></nav></header>
    <section className="hero"><div className="hero-inner"><div className="hero-copy"><p className="eyebrow">Cinématique premium · 01</p><h1 className="serif">Les actifs ont<br /><em>une histoire.</em><br />Donnez-lui du mouvement.</h1><p className="hero-intro">Vidéo cinématique pour actifs premium à partir de vos photos. Villas, yachts, jets privés, supercars : une présence à la hauteur de ce que vous présentez.</p><div className="hero-actions"><Link className="button lime" href="/auth">Créer mon premier film <ArrowRight size={15} /></Link><Link className="button secondary" href="#method">Voir comment ça marche</Link></div><div className="hero-note"><CheckIcon size={13} /> Upload manuel uniquement · aperçu filigrané gratuit</div></div><div className="hero-visual" aria-label="Aperçu d’un film d’actif premium"><div className="visual-card visual-main"><div className="visual-window" /></div><div className="visual-card visual-tag">Votre prochaine signature</div><div className="visual-card visual-caption">Une signature en mouvement.</div></div></div><div className="hero-index"><b>01</b> / 03</div></section>
    <div className="logo-strip"><span>Pour les lieux qui comptent</span><span>Agence Rivoli</span><span>Atelier 19</span><span>Habiter mieux</span></div>
    <section className="category-section"><div className="section-row"><div><p className="eyebrow">Une seule chaîne de création</p><h2 className="serif">Cinq façons de<br /><span>faire impression.</span></h2></div><p>Vous importez vos photos. Nous adaptons le regard, le rythme et le vocabulaire à chaque actif.</p></div><div className="category-grid"><Link href="/auth" className="category-tile category-villa"><span>01</span><strong>Villas</strong><small>Volumes & lumière</small></Link><Link href="/auth" className="category-tile category-rental"><span>02</span><strong>Locations</strong><small>Projection & quotidien</small></Link><Link href="/auth" className="category-tile category-yacht"><span>03</span><strong>Yachts</strong><small>Lignes & horizon</small></Link><Link href="/auth" className="category-tile category-jet"><span>04</span><strong>Jets privés</strong><small>Espace & altitude</small></Link><Link href="/auth" className="category-tile category-car"><span>05</span><strong>Supercars</strong><small>Design & puissance</small></Link></div></section>
    <section className="story-section" id="method"><div className="story-heading"><div><p className="eyebrow">Une autre façon de présenter</p><h2 className="serif">De la fiche froide<br />au <span>coup de cœur.</span></h2></div><p>Un bon film ne liste pas des caractéristiques. Il compose une sensation : la lumière du matin, le rythme d’une circulation, ce détail qui fait déjà se projeter.</p></div><div className="principles"><article className="principle"><span className="principle-number">01 — Le regard</span><h3>Un storyboard, pas un diaporama</h3><p>Notre IA lit vos photos comme un directeur artistique et imagine un fil narratif propre à chaque actif.</p></article><article className="principle"><span className="principle-number">02 — Le rythme</span><h3>Des images qui respirent</h3><p>Travellings subtils, transitions mesurées et durée juste : l’attention reste sur la signature, jamais sur l’effet.</p></article><article className="principle"><span className="principle-number">03 — La preuve</span><h3>Un film prêt à partager</h3><p>Prévisualisez, validez, puis exportez un format pensé pour vos annonces, vos réseaux et vos clients.</p></article></div></section>
    <section className="cta-band" id="pricing"><div><p className="eyebrow">Votre prochaine adresse</p><h2 className="serif">Faites visiter avant<br />d’ouvrir la porte.</h2></div><div><p>Commencez avec un aperçu local en quelques minutes. Passez au plan qui vous ressemble quand vous êtes prêt.</p><Link className="button" href="/auth">Entrer dans le studio <ArrowUpRight size={14} /></Link></div></section>
    <footer className="site-footer"><Brand /><span>© 2026 Maison Motion · Pensé pour les lieux singuliers.</span></footer>
  </main>;
}
